#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"AlwaysOnDM", {PERSISTENT, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | DEVELOPMENT_ONLY, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL, "1"}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT, STRING, "en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastAgnosPowerMonitorShutdown", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_DriverMonitoringUncertain", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSomResetTriggered", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSignatures", {CLEAR_ON_MANAGER_START, BYTES}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT, BOOL, "0"}},
    {"RecordFront", {PERSISTENT, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"ShowDebugInfo", {PERSISTENT, BOOL}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"Version", {PERSISTENT, STRING}},

    // kisapilot
    {"IsOpenpilotViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"KisaBlindSpotDetect", {PERSISTENT, BOOL, "1"}},
    {"KisaAutoShutdown", {PERSISTENT, INT, "12"}},
    {"KisaUIBrightness", {PERSISTENT, INT, "0"}},
    {"KisaUIVolumeBoost", {PERSISTENT, INT, "0"}},
    {"TimeFactorModHours", {PERSISTENT, STRING, "0"}},
    {"TimeFactorModMinutes", {PERSISTENT, STRING, "0"}},
    {"DoNotDisturbMode", {PERSISTENT, INT, "0"}},
    {"EnableRadarTracks", {PERSISTENT, INT, "0"}},
    {"RecordingRunning", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL, "0"}},
    {"RecordingTimePerVideo", {PERSISTENT, INT, "5"}},
    {"RecordingMaxFiles", {PERSISTENT, INT, "200"}},
    {"KisaHotspotOnBoot", {PERSISTENT, BOOL, "0"}},
    {"KisaMonitoringMode", {PERSISTENT, INT, "0"}},
    {"LFAButtonEngagement", {PERSISTENT, BOOL, "0"}},
    {"UseLegacyLaneModel", {PERSISTENT, INT, "2"}},
    {"KisaHDPuse", {PERSISTENT, BOOL, "1"}},
    {"AutoEnableSpeed", {PERSISTENT, INT, "5"}},
    {"KisaTurnSteeringDisable", {PERSISTENT, BOOL, "0"}},
    {"SteerWarningFix", {PERSISTENT, BOOL, "0"}},
    {"JustDoGearD", {PERSISTENT, BOOL, "0"}},
    {"NoSmartMDPS", {PERSISTENT, BOOL, "0"}},
    {"LdwsCarFix", {PERSISTENT, BOOL, "0"}},
    {"UseRadarValue", {PERSISTENT, BOOL, "1"}},
    {"DepartChimeAtResume", {PERSISTENT, BOOL, "0"}},
    {"KISALongAlt", {PERSISTENT, INT, "0"}},

    {"KisaLaneChangeSpeed", {PERSISTENT, INT, "20"}},
    {"KisaAutoLaneChangeDelay", {PERSISTENT, INT, "0"}},
    {"KisaSteerAngleCorrection", {PERSISTENT, FLOAT, "0.0"}},
    {"CameraOffsetAdj", {PERSISTENT, FLOAT, "0.04"}},
    {"SteerRatioAdj", {PERSISTENT, FLOAT, "10.0"}},
    {"LiveSteerRatioPercent", {PERSISTENT, INT, "0"}},
    {"SteerActuatorDelayAdj", {PERSISTENT, FLOAT, "0.15"}},
    {"SteerLimitTimerAdj", {PERSISTENT, FLOAT, "1.0"}},
    {"TireStiffnessFactorAdj", {PERSISTENT, FLOAT, "1.0"}},
    {"SteerMaxAdj", {PERSISTENT, INT, "384"}},
    {"SteerDeltaUpAdj", {PERSISTENT, INT, "3"}},
    {"SteerDeltaDownAdj", {PERSISTENT, INT, "7"}},
    {"KisaLiveTorque", {PERSISTENT, BOOL, "1"}},
    {"TorqueKp", {PERSISTENT, FLOAT, "1.0"}},
    {"TorqueKi", {PERSISTENT, FLOAT, "0.3"}},
    {"TorqueFriction", {PERSISTENT, FLOAT, "0.08"}},
    {"TorqueMaxLatAccel", {PERSISTENT, FLOAT, "3.0"}},
    {"TorqueAngDeadZone", {PERSISTENT, FLOAT, "1.0"}},
    {"LaneWidth", {PERSISTENT, FLOAT, "3.7"}},
    {"SpdLaneWidthSpd", {PERSISTENT, STRING, "0,31"}},
    {"SpdLaneWidthSet", {PERSISTENT, STRING, "2.8,3.5"}},
    {"LeftEdgeOffset", {PERSISTENT, FLOAT, "0.0"}},
    {"RightEdgeOffset", {PERSISTENT, FLOAT, "0.0"}},
    {"LeftCurvOffsetAdj", {PERSISTENT, INT, "0"}},
    {"RightCurvOffsetAdj", {PERSISTENT, INT, "0"}},
    {"KisaMaxAngleLimit", {PERSISTENT, INT, "80"}},
    {"SpeedCameraOffset", {PERSISTENT, BOOL, "0"}},
    {"AvoidLKASFaultEnabled", {PERSISTENT, BOOL, "1"}},
    {"AvoidLKASFaultMaxAngle", {PERSISTENT, INT, "85"}},
    {"AvoidLKASFaultMaxFrame", {PERSISTENT, INT, "89"}},

    {"KisaVariableCruise", {PERSISTENT, BOOL, "1"}},
    {"CruiseStatemodeSelInit", {PERSISTENT, INT, "1"}},
    {"CruiseOverMaxSpeed", {PERSISTENT, BOOL, "0"}},
    {"CruiseAutoRes", {PERSISTENT, BOOL, "0"}},
    {"AutoResOption", {PERSISTENT, INT, "0"}},
    {"AutoResCondition", {PERSISTENT, INT, "0"}},
    {"AutoResLimitTime", {PERSISTENT, INT, "0"}},
    {"AutoRESDelay", {PERSISTENT, INT, "1"}},
    {"StoppingDist", {PERSISTENT, FLOAT, "3.5"}},

    {"RESCountatStandstill", {PERSISTENT, INT, "35"}},
    {"KISACruiseSpammingInterval", {PERSISTENT, INT, "7"}},
    {"CruiseGapAdjust", {PERSISTENT, BOOL, "0"}},
    {"KISAEarlyStop", {PERSISTENT, BOOL, "1"}},
    {"CruiseSpammingSpd", {PERSISTENT, STRING, "50,80,110"}},
    {"CruiseSpammingLevel", {PERSISTENT, STRING, "15,10,5,0"}},
    {"SetSpeedPlus", {PERSISTENT, INT, "0"}},
    {"KisaCruiseGapSet", {PERSISTENT, INT, "4"}},
    {"CruiseGap1", {PERSISTENT, FLOAT, "1.1"}},
    {"CruiseGap2", {PERSISTENT, FLOAT, "1.2"}},
    {"CruiseGap3", {PERSISTENT, FLOAT, "1.3"}},
    {"CruiseGap4", {PERSISTENT, FLOAT, "1.5"}},
    {"DynamicTRGap", {PERSISTENT, INT, "0"}},
    {"DynamicTR0to20", {PERSISTENT, FLOAT, "1.1"}},
    {"DynamicTR20to40", {PERSISTENT, FLOAT, "1.2"}},
    {"DynamicTR40to60", {PERSISTENT, FLOAT, "1.3"}},
    {"DynamicTR60to80", {PERSISTENT, FLOAT, "1.4"}},
    {"DynamicTR80to110", {PERSISTENT, FLOAT, "1.5"}},

    {"CruiseSetwithRoadLimitSpeedEnabled", {PERSISTENT, BOOL, "0"}},
    {"CruiseSetwithRoadLimitSpeedOffset", {PERSISTENT, INT, "0"}},
    {"KISANaviSelect", {PERSISTENT, INT, "0"}},
    {"KisaSpeedLimitSignType", {PERSISTENT, INT, "0"}},
    {"KisaSpeedLimitOffset", {PERSISTENT, INT, "0"}},
    {"SafetyCamDecelDistGain", {PERSISTENT, INT, "0"}},
    {"KISASpeedBump", {PERSISTENT, BOOL, "0"}},
    {"StockNaviSpeedEnabled", {PERSISTENT, BOOL, "0"}},
    {"UseStockDecelOnSS", {PERSISTENT, BOOL, "0"}},
    {"CurvDecelOption", {PERSISTENT, INT, "2"}},
    {"OSMSpeedLimitEnable", {PERSISTENT, BOOL, "0"}},
    {"VCurvSpeedC", {PERSISTENT, STRING, "30,50,70,90"}},
    {"VCurvSpeedT", {PERSISTENT, STRING, "43,58,73,87"}},
    {"VCurvSpeedCMPH", {PERSISTENT, STRING, "20,30,45,60"}},
    {"VCurvSpeedTMPH", {PERSISTENT, STRING, "27,36,46,57"}},
    {"OCurvSpeedC", {PERSISTENT, STRING, "30,40,50,60,70"}},
    {"OCurvSpeedT", {PERSISTENT, STRING, "35,45,60,70,80"}},
    {"OSMCustomSpeedLimitC", {PERSISTENT, STRING, "30,40,50,60,70,90"}},
    {"OSMCustomSpeedLimitT", {PERSISTENT, STRING, "30,40,65,72,80,95"}},

    {"UFCModeEnabled", {PERSISTENT, BOOL, "0"}},
    {"UserSpecificFeature", {PERSISTENT, INT, "0"}},
    {"ShowDebugUI", {PERSISTENT, INT, "0"}},
    {"KisaEnableLogger", {PERSISTENT, BOOL, "0"}},
    {"PutPrebuiltOn", {PERSISTENT, BOOL, "0"}},
    {"KisaSSHLegacy", {PERSISTENT, BOOL, "1"}},
    {"KisaCanfdDebug", {PERSISTENT, INT, "0"}},
    {"KisaEnableUploader", {PERSISTENT, BOOL, "0"}},
    {"OnRoadRefresh", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"CarList", {PERSISTENT, STRING, "Select Your Car"}},
    {"GitCommits", {CLEAR_ON_MANAGER_START, STRING}},
    {"KisaPilotCurrentDescription", {PERSISTENT, STRING}},
    {"DrivingModel", {PERSISTENT, STRING, "DrivingModel"}},
    {"CarName", {PERSISTENT, STRING, ""}},
    {"KisaCANType", {PERSISTENT, STRING, "-"}},
    {"KisaSCCType", {PERSISTENT, STRING, "-"}},
};
