#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"AlwaysOnDM", {PERSISTENT, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | DEVELOPMENT_ONLY, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL, "1"}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT, STRING, "main_en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSomResetTriggered", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSignatures", {CLEAR_ON_MANAGER_START, BYTES}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT, BOOL, "0"}},
    {"RecordFront", {PERSISTENT, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"TermsVersion", {PERSISTENT, STRING}},
    {"TrainingVersion", {PERSISTENT, STRING}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"Version", {PERSISTENT, STRING}},

    {"IsOpenpilotViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"KisaAutoShutdown", {PERSISTENT, INT, "12"}},
    {"KisaAutoScreenOff", {PERSISTENT, STRING, "-2"}},
    {"KisaUIBrightness", {PERSISTENT, STRING, "0"}},
    {"KisaUIVolumeBoost", {PERSISTENT, STRING, "0"}},
    {"KisaEnableLogger", {PERSISTENT, BOOL, "0"}},
    {"KisaAutoResume", {PERSISTENT, BOOL, "1"}},
    {"KisaVariableCruise", {PERSISTENT, BOOL, "1"}},
    {"KisaLaneChangeSpeed", {PERSISTENT, INT, "20"}},
    {"KisaAutoLaneChangeDelay", {PERSISTENT, INT, "0"}},
    {"KisaSteerAngleCorrection", {PERSISTENT, INT, "0"}},
    {"PutPrebuiltOn", {PERSISTENT, BOOL, "0"}},
    {"LdwsCarFix", {PERSISTENT, BOOL, "0"}},
    {"LateralControlMethod", {PERSISTENT, INT, "3"}},
    {"CruiseStatemodeSelInit", {PERSISTENT, INT, "1"}},
    {"OuterLoopGain", {PERSISTENT, INT, "35"}},
    {"InnerLoopGain", {PERSISTENT, INT, "20"}},
    {"TimeConstant", {PERSISTENT, INT, "14"}},
    {"ActuatorEffectiveness", {PERSISTENT, INT, "20"}},
    {"Scale", {PERSISTENT, INT, "1500"}},
    {"LqrKi", {PERSISTENT, INT, "16"}},
    {"DcGain", {PERSISTENT, INT, "265"}},
    {"PidKp", {PERSISTENT, INT, "25"}},
    {"PidKi", {PERSISTENT, INT, "40"}},
    {"PidKd", {PERSISTENT, INT, "150"}},
    {"PidKf", {PERSISTENT, INT, "7"}},
    {"TorqueKp", {PERSISTENT, INT, "10"}},
    {"TorqueKf", {PERSISTENT, INT, "10"}},
    {"TorqueKi", {PERSISTENT, INT, "3"}},
    {"TorqueKd", {PERSISTENT, INT, "0"}},
    {"TorqueFriction", {PERSISTENT, INT, "80"}},
    {"TorqueMaxLatAccel", {PERSISTENT, INT, "30"}},
    {"TorqueAngDeadZone", {PERSISTENT, INT, "10"}},
    {"CameraOffsetAdj", {PERSISTENT, INT, "40"}},
    {"PathOffsetAdj", {PERSISTENT, INT, "0"}},
    {"SteerRatioAdj", {PERSISTENT, INT, "1375"}},
    {"SteerActuatorDelayAdj", {PERSISTENT, INT, "15"}},
    {"SteerLimitTimerAdj", {PERSISTENT, INT, "100"}},
    {"TireStiffnessFactorAdj", {PERSISTENT, INT, "85"}},
    {"SteerMaxAdj", {PERSISTENT, INT, "384"}},
    {"SteerDeltaUpAdj", {PERSISTENT, INT, "3"}},
    {"SteerDeltaDownAdj", {PERSISTENT, INT, "7"}},
    {"LeftCurvOffsetAdj", {PERSISTENT, INT, "0"}},
    {"RightCurvOffsetAdj", {PERSISTENT, INT, "0"}},
    {"DebugUi1", {PERSISTENT, BOOL, "0"}},
    {"DebugUi2", {PERSISTENT, BOOL, "0"}},
    {"DebugUi3", {PERSISTENT, BOOL, "0"}},
    {"LongLogDisplay", {PERSISTENT, BOOL, "0"}},
    {"KisaBlindSpotDetect", {PERSISTENT, BOOL, "1"}},
    {"KisaMaxAngleLimit", {PERSISTENT, INT, "80"}},
    {"KisaSteerMethod", {PERSISTENT, INT, "0"}},
    {"KisaMaxSteeringAngle", {PERSISTENT, INT, "90"}},
    {"KisaMaxDriverAngleWait", {PERSISTENT, FLOAT, "0.002"}},
    {"KisaMaxSteerAngleWait", {PERSISTENT, FLOAT, "0.001"}},
    {"KisaDriverAngleWait", {PERSISTENT, FLOAT, "0.001"}},
    {"KisaSpeedLimitOffset", {PERSISTENT, INT, "0"}},
    {"KisaLiveSteerRatio", {PERSISTENT, BOOL, "1"}},
    {"KisaDrivingRecord", {PERSISTENT, BOOL, "0"}},
    {"KisaTurnSteeringDisable", {PERSISTENT, BOOL, "0"}},
    {"CarModel", {PERSISTENT, STRING, ""}},
    {"KisaHotspotOnBoot", {PERSISTENT, BOOL, "0"}},
    {"KisaSSHLegacy", {PERSISTENT, BOOL, "1"}},
    {"CruiseOverMaxSpeed", {PERSISTENT, BOOL, "0"}},
    {"JustDoGearD", {PERSISTENT, BOOL, "0"}},
    {"LanelessMode", {PERSISTENT, INT, "2"}},
    {"SteerThreshold", {PERSISTENT, INT, "150"}},
    {"RecordingCount", {PERSISTENT, INT, "200"}},
    {"RecordingRunning", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL, "0"}},
    {"CruiseGapAdjust", {PERSISTENT, BOOL, "0"}},
    {"AutoEnable", {PERSISTENT, BOOL, "0"}},
    {"AutoEnableSpeed", {PERSISTENT, INT, "5"}},
    {"CruiseAutoRes", {PERSISTENT, BOOL, "0"}},
    {"AutoResOption", {PERSISTENT, INT, "0"}},
    {"AutoResCondition", {PERSISTENT, INT, "0"}},
    {"KisaMonitoringMode", {PERSISTENT, BOOL, "0"}},
    {"KisaMonitorEyesThreshold", {PERSISTENT, STRING, "45"}},
    {"KisaMonitorBlinkThreshold", {PERSISTENT, STRING, "75"}},
    {"UFCModeEnabled", {PERSISTENT, BOOL, "0"}},
    {"CommaStockUI", {PERSISTENT, INT, "0"}},
    {"KisaEnableUploader", {PERSISTENT, BOOL, "0"}},
    {"SteerWarningFix", {PERSISTENT, BOOL, "0"}},
    {"CruiseGap1", {PERSISTENT, INT, "11"}},
    {"CruiseGap2", {PERSISTENT, INT, "12"}},
    {"CruiseGap3", {PERSISTENT, INT, "13"}},
    {"CruiseGap4", {PERSISTENT, INT, "15"}},
    {"DynamicTRGap", {PERSISTENT, INT, "1"}},
    {"CustomTREnabled", {PERSISTENT, BOOL, "1"}},
    {"DynamicTRSpd", {PERSISTENT, STRING, "0,20,40,60,110"}},
    {"DynamicTRSet", {PERSISTENT, STRING, "1.1,1.2,1.3,1.4,1.5"}},
    {"LCTimingFactorUD", {PERSISTENT, STRING, "1"}},
    {"LCTimingFactor30", {PERSISTENT, INT, "30"}},
    {"LCTimingFactor60", {PERSISTENT, INT, "60"}},
    {"LCTimingFactor80", {PERSISTENT, INT, "80"}},
    {"LCTimingFactor110", {PERSISTENT, INT, "100"}},
    {"KisaUIBrightnessOff", {PERSISTENT, STRING, "10"}},
    {"LCTimingFactorEnable", {PERSISTENT, BOOL, "0"}},
    {"SafetyCamDecelDistGain", {PERSISTENT, INT, "0"}},
    {"KisaLiveTunePanelEnable", {PERSISTENT, BOOL, "0"}},
    {"BottomTextView", {PERSISTENT, STRING, "0"}},
    {"RadarLongHelper", {PERSISTENT, INT, "2"}},
    {"LiveSteerRatioPercent", {PERSISTENT, INT, "0"}},
    {"StoppingDistAdj", {PERSISTENT, BOOL, "0"}},
    {"ShowError", {PERSISTENT, BOOL, "1"}},
    {"AutoResLimitTime", {PERSISTENT, INT, "0"}},
    {"VCurvSpeedC", {PERSISTENT, STRING, "30,50,70,90"}},
    {"VCurvSpeedT", {PERSISTENT, STRING, "43,58,73,87"}},
    {"VCurvSpeedCMPH", {PERSISTENT, STRING, "20,30,45,60"}},
    {"VCurvSpeedTMPH", {PERSISTENT, STRING, "27,36,46,57"}},
    {"OCurvSpeedC", {PERSISTENT, STRING, "30,40,50,60,70"}},
    {"OCurvSpeedT", {PERSISTENT, STRING, "35,45,60,70,80"}},
    {"OSMCustomSpeedLimitC", {PERSISTENT, STRING, "30,40,50,60,70,90"}},
    {"OSMCustomSpeedLimitT", {PERSISTENT, STRING, "30,40,65,72,80,95"}},
    {"StockNaviSpeedEnabled", {PERSISTENT, BOOL, "0"}},
    {"KISANaviSelect", {PERSISTENT, INT, "0"}},
    {"OSMEnable", {PERSISTENT, BOOL, "0"}},
    {"OSMSpeedLimitEnable", {PERSISTENT, BOOL, "0"}},
    {"IgnoreCANErroronISG", {PERSISTENT, BOOL, "0"}},
    {"RESCountatStandstill", {PERSISTENT, INT, "25"}},
    {"KisaSpeedLimitOffsetOption", {PERSISTENT, INT, "0"}},
    {"KisaSpeedLimitSignType", {PERSISTENT, BOOL, "0"}},
    {"StockLKASEnabled", {PERSISTENT, BOOL, "0"}},
    {"SpeedLimitDecelOff", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"CurvDecelOption", {PERSISTENT, INT, "2"}},
    {"StandstillResumeAlt", {PERSISTENT, BOOL, "0"}},
    {"AutoRESDelay", {PERSISTENT, INT, "1"}},
    {"UseRadarTrack", {PERSISTENT, BOOL, "0"}},
    {"RoutineDriveOn", {PERSISTENT, BOOL, "0"}},
    {"RoutineDriveOption", {PERSISTENT, STRING, "KISA"}},
    {"RoadList", {PERSISTENT, STRING, "RoadName1,+0.0,RoadName2,-0.0\nRoadName3,30,RoadName4,60"}},
    {"LaneWidth", {PERSISTENT, INT, "37"}},
    {"SpdLaneWidthSpd", {PERSISTENT, STRING, "0,31"}},
    {"SpdLaneWidthSet", {PERSISTENT, STRING, "2.8,3.5"}},
    {"CloseToRoadEdge", {PERSISTENT, BOOL, "0"}},
    {"LeftEdgeOffset", {PERSISTENT, INT, "0"}},
    {"RightEdgeOffset", {PERSISTENT, INT, "0"}},
    {"AvoidLKASFaultEnabled", {PERSISTENT, BOOL, "1"}},
    {"AvoidLKASFaultMaxAngle", {PERSISTENT, INT, "85"}},
    {"AvoidLKASFaultMaxFrame", {PERSISTENT, INT, "89"}},
    {"UseStockDecelOnSS", {PERSISTENT, BOOL, "0"}},
    {"AnimatedRPM", {PERSISTENT, BOOL, "1"}},
    {"AnimatedRPMMax", {PERSISTENT, STRING, "3600"}},
    {"NoSmartMDPS", {PERSISTENT, BOOL, "0"}},
    {"UserSpecificFeature", {PERSISTENT, INT, "0"}},
    {"KisaWakeUp", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"OnRoadRefresh", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"StoppingDist", {PERSISTENT, INT, "35"}},
    {"SpeedCameraOffset", {PERSISTENT, BOOL, "0"}},
    {"GitCommits", {CLEAR_ON_MANAGER_START, STRING}},
    {"StopAtStopSign", {PERSISTENT, BOOL, "0"}},
    {"KISASpeedBump", {PERSISTENT, BOOL, "0"}},
    {"KISAEarlyStop", {PERSISTENT, BOOL, "1"}},
    {"ExternalDeviceIP", {PERSISTENT, STRING}},
    {"ExternalDeviceIPAuto", {PERSISTENT, INT, "1"}},
    {"ExternalDeviceIPNow", {CLEAR_ON_MANAGER_START, STRING}},
    {"DoNotDisturbMode", {PERSISTENT, STRING, "0"}},
    {"DepartChimeAtResume", {PERSISTENT, BOOL, "0"}},
    {"CruiseGapBySpdOn", {PERSISTENT, BOOL, "0"}},
    {"CruiseGapBySpdSpd", {PERSISTENT, STRING, "25,55,130"}},
    {"CruiseGapBySpdGap", {PERSISTENT, STRING, "1,2,3,4"}},
    {"CruiseSetwithRoadLimitSpeedEnabled", {PERSISTENT, BOOL, "0"}},
    {"CruiseSetwithRoadLimitSpeedOffset", {PERSISTENT, INT, "0"}},
    {"KISADebug", {PERSISTENT, BOOL, "0"}},
    {"KisaLiveTorque", {PERSISTENT, BOOL, "1"}},
    {"SetSpeedPlus", {PERSISTENT, INT, "0"}},
    {"KISALongAlt", {PERSISTENT, INT, "0"}},
    {"LowUIProfile", {PERSISTENT, BOOL, "0"}},
    {"RunCustomCommand", {CLEAR_ON_MANAGER_START, STRING}},
    {"CruiseSpammingSpd", {PERSISTENT, STRING, "50,80,110"}},
    {"CruiseSpammingLevel", {PERSISTENT, STRING, "15,10,5,0"}},
    {"KISACruiseSpammingInterval", {PERSISTENT, INT, "7"}},
    {"KISACruiseSpammingBtnCount", {PERSISTENT, INT, "1"}},
    {"KisaCruiseGapSet", {PERSISTENT, INT, "4"}},
    {"KisaPilotCurrentDescription", {PERSISTENT, STRING}},
    {"UseLegacyLaneModel", {PERSISTENT, INT, "2"}},
    {"GitCommitRemote", {PERSISTENT, STRING, "0000000000000000000000000000000000000000"}},
    {"GitCommitRemoteDate", {PERSISTENT, STRING, "00-00"}},
    {"DrivingModel", {PERSISTENT, STRING, "DrivingModel"}},
    {"UseRadarValue", {PERSISTENT, BOOL, "1"}},
    {"ErrorOccurred", {CLEAR_ON_MANAGER_START, BOOL}},
    {"RegenBrakeFeature", {PERSISTENT, STRING, "0"}},
    {"RegenBrakeFeatureOn", {PERSISTENT, BOOL, "0"}},
    {"LFAButtonEngagement", {PERSISTENT, BOOL, "0"}},
    {"TimeFactorModHours", {PERSISTENT, STRING, "0"}},
    {"TimeFactorModMinutes", {PERSISTENT, STRING, "0"}},
};
